### ISSUE TITLE
Moving selections to the furthest one.

### ISSUE THREAD

**Issue by Rapptz** [philippotto/Sublime-MultiEditUtils#11]
Hello. I have a feature request that I think would be useful to have. I hope it's in the scope of this plug-in.

It'd be cool if there was a way to move all the cursors to the furthest one.

Example:

before:

```
absjdbsahd ajsh|djashas
shajs|dh hajshjsahd
jhasdjha|k dakshdk
jahsdjas dja|hsjhhjdas
```

after:

```
absjdbsahd ajsh|djashas
shajsdh hajshjs|ahd
jhasdjhak daksh|dk
jahsdjas djahsj|hhjdas
```

I'm also not sure if this is possible. Sorry if it isn't.

**Comment by eorroe** [comment]
I'm just looking through the issues to learn more about this plugin, since I discovered something else today after more than a year with this, but @Rapptz you might want to look at [Column Select](https://packagecontrol.io/packages/Column%20Select) so in your case you would select all the `|` delete them, then hit esc and then use Column Select. Yet this wouldn't work if the lines are split, but hope this helps for some cases.
