### ISSUE TITLE
[Enhancement] Cycle through multiple selections

### ISSUE THREAD

**Issue by rbhalla** [philippotto/Sublime-MultiEditUtils#14]
Some times you have multiple selections that you don't want to edit all at the same time. Consider the following
```
if (foo == bar)
```

I then duplicate the line multiple tines and select each instance of `bar`. I'd like to be able to go to the first one, change it, then automatically go to the second selection using some sort of key combination and change that one, until I have reached the end.

I think this could be quite a fitting addition to your already brilliant plugin, what do you think?

**Comment by philippotto** [comment]
If I understand the scenario correctly, this is already covered by ST's standard features. Just select the first instance, then hit ctrl+f (the search field will automatically be filled with the selection). Now, hit enter to go to the next occurrence. If you want to edit the occurrence, you have to hit escape in order to close the search box. Going to the following occurrences is as easy as hitting F3 (on Windows). The command is called `find_next`.

Or am I missing some improvements that could be added by MultiEditUtils?

**Comment by rbhalla** [comment]
Hi,

That does work when you are selecting the same phrase, but if you already have multiple selections and you just want to cycle through and add/edit this doesn't work.

**Comment by philippotto** [comment]
OK, that's right. But why are you creating multiple selections in the first place when you want to edit them separately? I'm afraid I don't get the use case, yet. The actual purpose of multiple selections is that you can edit all selections at the same time. Having a feature to edit them manually defeats the purpose a bit, I think? But maybe you can explain the use case a little more detailed and within context.

**Comment by rbhalla** [comment]
I think the emphasis here is on having multiple cursors at specific locations that you want to jump around. It is less about the selection and more about where all my cursors are.

For example, say I have a basic switch statement:
```
switch(foo) {
   case 'bar':
   default:
}
```

I then want to create more cases. I could easily duplicate the the `case 'bar'` line multiple times.
```
switch(foo) {
   case 'bar':
   case 'bar':
   case 'bar':
   default:
}
```

Then select each instance of `'bar'` and press left. I now have 3 cursors at points that I want to write/replace words.

**Comment by philippotto** [comment]
For this use case the multiple selections were created by using the same identifier (`bar`) which is why my first suggestion to use `find_next` would also work.
The problem I'm currently having with this feature request is that if you create multiple selections manually (i.e. _not_ by using ctrl/cmd + d), then you could do your modifications manually _without_ creating a multiple selection at all.

So instead of doing
- create region 1
- create region 2
- jump to region 1
- modify region 1
- jump to region 2
- modify region 2

You could simply do
- jump to desired place 1
- modify
- jump to desired place 2
- modify

Apart from that, I would suggest the following workflow for your last use case:

![meu-usecase](https://cloud.githubusercontent.com/assets/2486553/6116440/e4fb1904-b0ac-11e4-956f-9113afce3702.gif)

But I'm willing to change my mind, if you provide another usecase where this would be a killer feature :)

**Comment by eorroe** [comment]
or this package would help: https://packagecontrol.io/packages/MarkAndMove

(you might have to create the keybindings yourself, at least I had to, and now I use it all the time) 

@philippotto thanks for the package by the way.

**Comment by philippotto** [comment]
@eorroe Perfect, this should match the needs of @rbhalla. Thank you for mentioning this package!

**Comment by eorroe** [comment]
You're welcome. @philippotto

**Comment by eorroe** [comment]
I realized you created this feature, and just discovered it today can't believe I haven't been using it. I'm on windows for me its `ctrl+alt+d` (Selections as Fields) I'm gonna use this more often can't believe I just discovered this after more than a year with this bad ass plugin
