### ISSUE TITLE
Disable Super+Alt+R when widgets are shown

### ISSUE THREAD

**Issue by certainlyakey** [philippotto/Sublime-MultiEditUtils#15]
Hello, thanks for a great plugin!

I discovered that on Mac <kbd>Super+Alt+R</kbd> shortcut of MEU overwrites the default binding inside find&replace panels to change regex search mode. This binding is set with `"key": "setting.is_widget", "operator": "equal", "operand": true` context, so the MEU shortcut possibly should just be set with the same context but `"operand":false` to avoid conflicting with the default command in find/replace panel.

**Comment by philippotto** [comment]
Hi @certainlyakey! I'm glad you like the plugin. Thanks for pointing out this misbehavior. On my machine <kbd>Alt+R</kbd> toggles the regex search mode, which is why I didn't experience the problem. But I fixed it, now. Should work as soon as your ST instance pulls the newest version of this package :)
