### ISSUE TITLE
On OSX, super+alt+s is already reserved for Save All

### ISSUE THREAD

**Issue by elado** [philippotto/Sublime-MultiEditUtils#18]
Consider changing the default.

I had to override it back on `Sublime Text 3/Packages/User/Default (OSX).sublime-keymap` with:

```json
	{ "keys": ["super+alt+s"], "command": "save_all" },
```

**Comment by philippotto** [comment]
Thanks for opening this issue. I wasn't aware of that. It was probably not a good idea to include default shortcuts for all the features of MEU, since conflicts are bound to happen. For new features I don't do this anymore.

Changing the keybinding would potentially be unconvenient for users who are already used to this keybinding. Additionally, it raises the risk of a new keybinding conflict. That is why, I would put this issue on hold to see if other users would also like to have the default changed or removed.

Thanks again for opening this issue!

**Comment by philippotto** [comment]
I'm closing this for now, since no one else complained so far, and due to the reasons stated in my previous posts.
