### ISSUE TITLE
I miss you

### ISSUE THREAD

**Issue by dc-avasilev** [philippotto/Sublime-MultiEditUtils#27]
Please insert the plug-in: Atom
I had to cancel use on Sublime text. Since too many bugs to Ububntu 16.04LTS with the Russian language.

**Comment by philippotto** [comment]
Sorry, I don't have the time and motivation for porting this package to Atom. Atom's slowness makes fancy multi-selection edits very unenjoyable for me which is why I don't feel like porting the package.

Couldn't you switch your ubuntu installation to the english language if that's the only problem?
